version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.dockerfile
    image: nginx:1.0.0
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/server_http.conf:/etc/nginx/server_http.conf:ro
      - ./config/server_https.conf:/etc/nginx/server_https.conf:ro
      - ./config/ssl:/etc/nginx/ssl
      - ./config/.htpasswd:/etc/nginx/.htpasswd
      - ./public:/etc/nginx/html
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge